@startuml

class Transport {
  +Long id
  +String name
  +String type
}

class ParkingSlot {
  +Long id
  +String name
  +Boolean availability
}

class Payment {
  +Long id
  +String transport_id
  +String slot_id
  +String transportName
  +String slotName
  +int price
}

Payment --> Transport : transport_id (FK)
Payment --> ParkingSlot : slot_id (FK)

@enduml
