spring:
  application:
    name: zuul-service

server:
  port: 8000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

zuul:
  prefix: /api
  routes:
    transport-service:
      path: /transport/**
      serviceId: transport-service
    parkingslot-service:
      path: /parkingslot/**
      serviceId: parkingslot-service
    payment-service:
      path: /payment/**
      serviceId: payment-service

  # Timeout settings for Zuul
  host:
    socket-timeout-millis: 60000  # Socket timeout (60 seconds)
    connect-timeout-millis: 60000 # Connection timeout (60 seconds)

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000  # Hystrix timeout (60 seconds)
