spring:
  application:
    name: zuul-service

server:
  port: 8000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

Zuul:
  prefix: /api
  routes:
    customer-service:
      path: /customer/**
      serviceId: CUSTOMER-SERVICE
    order-service:
      path: /order/**
      serviceId: ORDER-SERVICE
    transport-service:
      path: /transport/**
      serviceId: TRANSPORT-SERVICE
    parkingslot-service:
      path: /parkingslot/**
      serviceId: PARKINGSLOT-SERVICE
    payment-service:
      path: /payment/**
      service-id: PAYMENT-SERVICE